### ISSUE TITLE
Error during dockergento composer install

### ISSUE THREAD

**Issue by tarasyyyk** [ModestCoders/magento2-dockergento#53] opened 2019-07-15 14:12 UTC
This error happens when running `dockergento composer install`:
![1  bash 2019-07-15 17-12-49](https://user-images.githubusercontent.com/20100011/61222672-d2922d80-a723-11e9-86b8-64b8de3a9207.jpg)

**Comment by danielozano** [comment] 2019-07-26 22:20
Hi @tarasyyyk sometimes when you update the files `compose.lock` and `compose.json` via composer commands they get corrupted, running `dockergento restart` should work.

To check if the file is corrupted just log in into the container with `dockergento bash` and run `ls`, you should see something like `???` as file size.

Hope it works.

**Comment by tarasyyyk** [comment] 2019-08-05 14:02
@danielozano the problem was in missing lib folder on container.
Adding `- ./lib:/var/www/html/lib:delegated` to phpfpm's volumes in file `docker-compose.dev.mac.yml` solved problem.
This occurred only on Mac systems. Please, add this line to `docker-compose.dev.mac.yml` so future developers on macOS shouldn't spend 3h solving this problem.

**Comment by danielozano** [comment] 2019-08-06 05:46
Hi again @tarasyyyk I'm not able to reproduce such problem, if you read my previous response you will see that the problem has been probably fixed because you've restarted the containers.

You don't need to bind lib folder, because it's already generated inside the container, only if you want to modify the content but this won't make the docker setup work if you have the problem I explained you before.

**Comment by tarasyyyk** [comment] 2019-08-06 12:18
Yes, you right. This is not the right issue for it.
My Magento 2 installation completed successfully but static files wasn't loading because of missing lib folder. I didn't find any related issue, should I create one?

**Comment by danielozano** [comment] 2019-08-18 11:41
Hi @tarasyyyk feel free to open any issue you need! But please attach all the possible information for helping us to reproduce your problem!

I'm closing this issue, feel free to reopen it if you have any news.

**Closed by danielozano** 2019-08-18 11:41 UTC
